//
// Created by atomr on 7/18/2025.
//

#ifndef COMPAT_WRAPPERS_H
#define COMPAT_WRAPPERS_H

#define COMPAT_PTRTYPE(COMPAT_CLASS_NAME) \
C_##COMPAT_CLASS_NAME##_Ptr

#define COMPAT_CONSTRUCTOR(COMPAT_CLASS_NAME) \
COMPAT_PTRTYPE(COMPAT_CLASS_NAME) make_##COMPAT_CLASS_NAME(D_##COMPAT_CLASS_NAME dc)

#define COMPAT_DESTRUCTOR(COMPAT_CLASS_NAME) \
void destroy_##COMPAT_CLASS_NAME(COMPAT_PTRTYPE(COMPAT_CLASS_NAME) toDestroy)

#define COMPAT_FOR(COMPAT_CLASS_NAME)                \
typedef void* COMPAT_PTRTYPE(COMPAT_CLASS_NAME); \
COMPAT_CONSTRUCTOR(COMPAT_CLASS_NAME);           \
COMPAT_DESTRUCTOR(COMPAT_CLASS_NAME);


#endif //COMPAT_WRAPPERS_H
